"""empty message

Revision ID: 3b8b56daa0e4
Revises: f102a471a37b
Create Date: 2024-03-29 21:31:38.501367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b8b56daa0e4'
down_revision = 'f102a471a37b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_username', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('recipient_username', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('recipient_username')
        batch_op.drop_column('sender_username')

    # ### end Alembic commands ###
