""" added meal timestamp

Revision ID: 5f4dad58e440
Revises: 7f8c62623f43
Create Date: 2024-04-26 17:38:35.640854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4dad58e440'
down_revision = '7f8c62623f43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meal_logged_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('meal_logged_at')

    # ### end Alembic commands ###
