"""Added Join Code to meal model to enable athletes to join teams.
 This code will be 6 digits and will be changeable by the owner

Revision ID: 5f676f765fc8
Revises: 19985f76fac0
Create Date: 2024-04-09 21:15:40.946276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f676f765fc8'
down_revision = '19985f76fac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_code', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_team_join_code', ['join_code'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint('uq_team_join_code', type_='unique')
        batch_op.drop_column('join_code')


    # ### end Alembic commands ###
