"""empty message

Revision ID: 6ffe2b536428
Revises: b938203626a5
Create Date: 2024-04-25 16:11:24.046309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ffe2b536428'
down_revision = 'b938203626a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('meal_username', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('meal_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('notification_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'conversation', ['cid'], ['conversation_id'])
        batch_op.create_foreign_key(None, 'meal', ['meal_id'], ['meal_id'])
        batch_op.drop_column('other_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notification_ibfk_1', 'user', ['other_user_id'], ['user_id'])
        batch_op.drop_column('meal_id')
        batch_op.drop_column('meal_username')
        batch_op.drop_column('cid')

    # ### end Alembic commands ###
