"""Initial baseline migration

Revision ID: 755f1d4ecc8e
Revises: 
Create Date: 2024-04-30 19:02:56.309124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755f1d4ecc8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=15), nullable=False),
        sa.Column('hashed_password', sa.String(length=128), nullable=False),
        sa.Column('join_date', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('account_type', sa.String(length=35), nullable=False),
        sa.Column('profile_picture_url', sa.String(length=128), nullable=True),
        sa.Column('first_name', sa.String(length=20), nullable=True),
        sa.Column('last_name', sa.String(length=20), nullable=True),
        sa.Column('bio', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('user_id'),
        sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)

    op.create_table('conversation',
        sa.Column('conversation_id', sa.Integer(), nullable=False),
        sa.Column('last_used_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('last_message_text', sa.String(length=500), nullable=False),
        sa.Column('unread_message', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.Column('last_message_sender_username', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('conversation_id')
    )

    op.create_table('meal',
        sa.Column('meal_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('logged_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('image_url', sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.user_id']),
        sa.PrimaryKeyConstraint('meal_id')
    )

    op.create_table('team',
        sa.Column('team_id', sa.Integer(), nullable=False),
        sa.Column('team_name', sa.String(length=20), nullable=False),
        sa.Column('capacity', sa.Integer(), nullable=False),
        sa.Column('num_athletes', sa.Integer(), nullable=False, server_default = sa.text('0')),
        sa.Column('join_code', sa.Integer(), nullable=True),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.ForeignKeyConstraint(['owner_id'], ['user.user_id']),
        sa.PrimaryKeyConstraint('team_id'),
        sa.UniqueConstraint('team_name'),
        sa.UniqueConstraint('join_code')
    )

    op.create_table('message',
        sa.Column('message_id', sa.Integer(), nullable=False),
        sa.Column('sender_id', sa.Integer(), nullable=False),
        sa.Column('sender_username', sa.String(length=50), nullable=False),
        sa.Column('recipient_id', sa.Integer(), nullable=False),
        sa.Column('recipient_username', sa.String(length=50), nullable=False),
        sa.Column('message_text', sa.String(length=500), nullable=False),
        sa.Column('sent_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('conversation_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['conversation_id'], ['conversation.conversation_id']),
        sa.ForeignKeyConstraint(['recipient_id'], ['user.user_id']),
        sa.ForeignKeyConstraint(['sender_id'], ['user.user_id']),
        sa.PrimaryKeyConstraint('message_id')
    )

    op.create_table('notification',
        sa.Column('notification_id', sa.Integer(), nullable=False),
        sa.Column('header', sa.String(length=100), nullable=True),
        sa.Column('body', sa.String(length=500), nullable=True),
        sa.Column('is_new', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.Column('timestamp', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('variant', sa.String(length=30), nullable=True),
        sa.Column('cid', sa.Integer(), nullable=True),
        sa.Column('meal_username', sa.String(length=50), nullable=True),
        sa.Column('meal_id', sa.Integer(), nullable=True),
        sa.Column('meal_logged_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.user_id']),
        sa.ForeignKeyConstraint(['cid'], ['conversation.conversation_id']),
        sa.ForeignKeyConstraint(['meal_id'], ['meal.meal_id']),
        sa.PrimaryKeyConstraint('notification_id')
    )

    op.create_table('comment',
        sa.Column('comment_id', sa.Integer(), nullable=False),
        sa.Column('poster_id', sa.Integer(), sa.ForeignKey('user.user_id'), nullable=False),
        sa.Column('poster_username', sa.String(length=50), nullable=False),
        sa.Column('meal_id', sa.Integer(), sa.ForeignKey('meal.meal_id'), nullable=False),
        sa.Column('comment_text', sa.String(length=500), nullable=False),
        sa.Column('commented_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.PrimaryKeyConstraint('comment_id')
    )

    # Create many-to-many relational tables
    op.create_table('team_admins',
        sa.Column('team_id', sa.Integer(), sa.ForeignKey('team.team_id'), primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('user.user_id'), primary_key=True)
    )

    op.create_table('team_athletes',
        sa.Column('team_id', sa.Integer(), sa.ForeignKey('team.team_id'), primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('user.user_id'), primary_key=True)
    )

    op.create_table('conversation_users',
        sa.Column('conversation_id', sa.Integer(), sa.ForeignKey('conversation.conversation_id', ondelete='CASCADE'), primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('user.user_id', ondelete='CASCADE'), primary_key=True),
        sa.Column('joined_at', sa.DateTime(), default=sa.func.now(), nullable=False)
    )


    # ### end Alembic commands ###



    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop all dependent tables or those with foreign key relationships first
    op.drop_table('notification')
    op.drop_table('message')
    op.drop_table('comment')

    # Drop many-to-many relational tables
    op.drop_table('conversation_users')
    op.drop_table('team_athletes')
    op.drop_table('team_admins')

    # Now drop the core entity tables
    op.drop_table('team')
    op.drop_table('meal')
    op.drop_table('conversation')
    
    
    # Drop user table and its index
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###

    # ### end Alembic commands ###



