"""empty message

Revision ID: 7f8c62623f43
Revises: 6ffe2b536428
Create Date: 2024-04-25 16:24:46.131117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f8c62623f43'
down_revision = '6ffe2b536428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unread_message', sa.Boolean(), nullable=False, ))
        batch_op.add_column(sa.Column('last_message_sender_username', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_column('last_message_sender_username')
        batch_op.drop_column('unread_message')

    # ### end Alembic commands ###
