""" Added Comment model
Revision ID: 9b446f16d2e9
Revises: bab8ad4ade2c
Create Date: 2024-03-24 16:32:41.318915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision = '9b446f16d2e9'
down_revision = 'bab8ad4ade2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('poster_id', sa.Integer(), nullable=False),
    sa.Column('poster_username', sa.String(length = 50), nullable = False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.String(length=500), nullable=False),
    sa.Column('commented_at', sa.DateTime(), nullable=False, server_default= func.now()),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.meal_id'], ),
    sa.ForeignKeyConstraint(['poster_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
