"""Updated default values for DateTime columns. Set default of team.num_athletes to 0, fixed meal description.

Revision ID: bab8ad4ade2c
Revises: 35d1e36cc0e2
Create Date: 2024-03-17 13:52:46.460827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision = 'bab8ad4ade2c'
down_revision = '35d1e36cc0e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=500),
               nullable=True)
        batch_op.alter_column('logged_at',
                existing_type = mysql.DATETIME(),
                nullable = False,
                server_default = func.now())
        
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('join_date', existing_type = mysql.DATETIME(),
                              nullable = False,
                              server_default = func.now())
        batch_op.alter_column( 'account_type',
                existing_type=sa.String(length=35),
                server_default='standard',
                existing_nullable=False)

        
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('created_at', existing_type = mysql.DATETIME(),
                              nullable = False, 
                              server_default = func.now())
        batch_op.alter_column('num_athletes', existing_type = sa.Integer(),
                              nullable = False, 
                              server_default = sa.text('0'))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('num_athletes', existing_type=sa.Integer(),
                              nullable=True, server_default=None)
        batch_op.alter_column('created_at', existing_type=mysql.DATETIME(),
                              nullable=True, server_default=None)
        
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('join_date', existing_type=mysql.DATETIME(),
                              nullable=True, server_default=None)
        
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.alter_column('logged_at', existing_type=mysql.DATETIME(),
                              nullable=True, server_default=None)
        batch_op.alter_column('description', existing_type=sa.String(length=500),
                              type_=mysql.DATETIME(), nullable=False)
    # ### end Alembic commands ###
