"""empty message Added profile picture to convo for less queries 

Revision ID: fcb896b0030a
Revises: 5f4dad58e440
Create Date: 2024-04-28 15:33:01.528134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb896b0030a'
down_revision = '5f4dad58e440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_message_sender_profile_picture_url', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_column('last_message_sender_profile_picture_url')

    # ### end Alembic commands ###
